[package]
name = "phoenix"
version = "0.1.0"
authors = ["Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"

[dependencies]
merlin = "2.0"
rand = "^0.7"
tonic = "^0.1"
sodiumoxide = "0.2"
sha2 = "0.8"
prost = "0.6"
tracing = "0.1"
hex = "^0.4"
kelvin = "0.11.2"
kelvin-radix = "0.7"
kelvin-hamt = "0.8"
bytehash = "0.2"
lazy_static = "1.4"
num-traits = "0.2"

[dependencies.algebra]
git = "https://github.com/scipr-lab/zexe/"
features = ["parallel"]

[dependencies.poly-commit]
git = "https://github.com/scipr-lab/poly-commit"
branch = "master"

[dependencies.ff-fft]
git = "https://github.com/scipr-lab/zexe/"

[dependencies.hades252]
git = "https://github.com/dusk-network/Hades252.git"
branch = "plonk_zexe"

[dependencies.plonk]
git = "https://github.com/dusk-network/plonk.git"
branch = "fast_prover_zexe"

[build-dependencies]
tonic-build = { version = "0.1", default-features = false, features = ["transport"] }
