[package]
name = "phoenix"
version = "0.1.0"
authors = ["Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { version = "2.0", features = ["serde"] }
merlin = "2.0"
rand = "^0.7"
tonic = "^0.1"
sodiumoxide = "0.2"
sha2 = "0.8"
prost = "0.6"
tracing = "0.1"
hex = "^0.4"
kelvin = "0.11.2"
kelvin-radix = "0.7"
kelvin-hamt = "0.8"

[dev-dependencies]
lazy_static = "1.4"


[build-dependencies]
tonic-build = { version = "0.1", default-features = false, features = ["transport"] }

[dependencies.bulletproofs]
git = "https://github.com/dusk-network/bulletproofs.git"
branch = "develop"
features = ["yoloproofs"]

[dependencies.hades252]
git = "https://github.com/dusk-network/Hades252.git"
branch = "master"

[dependencies.poseidon252]
git = "https://github.com/dusk-network/Poseidon252.git"
branch = "master"
