[package]
name = "phoenix"
version = "0.1.0"
authors = ["Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { version = "1.0", features = ["serde"] }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
merlin = "1.3"

[dev-dependencies]
lazy_static = "1.4"
bincode = "1.2"

[dependencies.bulletproofs]
git = "https://github.com/dalek-cryptography/bulletproofs"
branch = "develop"
features = ["yoloproofs"]
