[package]
name = "phoenix"
version = "0.1.0"
authors = ["Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { version = "2.0", features = ["serde"] }
merlin = "2.0"
rand = "^0.7"
serde = { version = "1.0", features = ["derive"] }
sodiumoxide = "0.2"
sha2 = "0.8"

[dev-dependencies]
bincode = "1.2"
lazy_static = "1.4"

[dependencies.bulletproofs]
git = "https://github.com/dusk-network/bulletproofs.git"
branch = "dalek-v2"
features = ["yoloproofs"]

[dependencies.hades252]
git = "https://github.com/dusk-network/Hades252.git"
branch = "dalek-v2"
