[package]
name = "dusk-phoenix"
version = "0.1.0"
authors = ["Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { version = "1.0", features = ["serde"] }
dusk-tlv = { git = "https://github.com/dusk-network/dusk-tlv" }
log = "0.4"
rand = "0.7"
serde = "1.0"
merlin = "1.3"

[dependencies.bulletproofs]
git = "https://github.com/dalek-cryptography/bulletproofs"
branch = "develop"
features = ["yoloproofs"]
